#!/bin/sh

module="mlbuf"
device="mlbuf"
mode="664"

# Group: since distributions do it differently, look for wheel or use staff.
if grep -q '^staff:' /etc/group; then
    group="staff"
else
    group="wheel"
fi

# Invoke insmod with all provided arguments. Use a pathname, as insmod doesn't
# look in . by default.
/sbin/insmod ./$module.ko $* || exit 1

# Retrieve the device major number.
major=$(awk "\$2==\"$module\" {print \$1}" /proc/devices)

# Remove stale nodes and replace them, then give gid and perms.

# Usually a load script is shorter; mlbuf just has a lot of associated devices.

rm -f /dev/${device}[0-3]
mknod /dev/${device}0 c $major 0
mknod /dev/${device}1 c $major 1
mknod /dev/${device}2 c $major 2
mknod /dev/${device}3 c $major 3
ln -sf ${device}0 /dev/${device}
chgrp $group /dev/${device}[0-3] 
chmod $mode  /dev/${device}[0-3]

